# Gradle Properties
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Environment Properties
minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.109

## Mod Properties
mod_id=pumpkinpatched
mod_name=Pumpkin Patched
mod_license=GNU General Public License v3 (GPLv3)
mod_version=26.1.2-1.0.0
mod_group_id=site.scalarstudios.pumpkinpatched
